import { readFile } from "fs/promises";
import { join } from "path";
import { fileURLToPath } from "url";
import { dirname } from "path";
import bookRepository from "../src/repositories/BookRepository.js";
import unitRepository from "../src/repositories/UnitRepository.js";
import logger from "../src/utils/logger.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * Attempt to auto-transform shamela_crawler format
 * This is a simplified version - use transform_shamela_json.js for better results
 */
function attemptAutoTransform(rawData) {
    let bookData = Array.isArray(rawData) ? rawData[0] : rawData;
    
    const transformed = {
        title: bookData.title || bookData.name || "Untitled Book",
        author: bookData.author || bookData.writer || null,
        description: bookData.description || bookData.summary || null,
        category: bookData.category || bookData.type || null,
        language: bookData.language || "ar",
        units: [],
    };

    // Try to extract units from various structures
    if (bookData.units && Array.isArray(bookData.units)) {
        transformed.units = bookData.units;
    } else if (bookData.chapters && Array.isArray(bookData.chapters)) {
        let unitIndex = 1;
        bookData.chapters.forEach((chapter) => {
            if (chapter.content && Array.isArray(chapter.content)) {
                chapter.content.forEach((item) => {
                    transformed.units.push({
                        index: unitIndex++,
                        heading: chapter.title || null,
                        text: item.text || item.content || String(item || ""),
                    });
                });
            } else if (chapter.text || chapter.content) {
                transformed.units.push({
                    index: unitIndex++,
                    heading: chapter.title || null,
                    text: chapter.text || chapter.content || "",
                });
            }
        });
    } else if (bookData.content && Array.isArray(bookData.content)) {
        transformed.units = bookData.content.map((item, idx) => ({
            index: idx + 1,
            heading: item.title || null,
            text: item.text || item.content || String(item || ""),
        }));
    }

    transformed.units = transformed.units
        .map((unit, idx) => ({
            index: unit.index !== undefined ? unit.index : idx + 1,
            heading: unit.heading || null,
            text: String(unit.text || "").trim(),
        }))
        .filter((unit) => unit.text.length > 0);

    return transformed;
}

/**
 * Import books from JSON files generated by shamela_crawler
 *
 * Expected JSON structure:
 * {
 *   "title": "Book Title",
 *   "author": "Author Name",
 *   "description": "Book description",
 *   "category": "Category",
 *   "units": [
 *     {
 *       "index": 1,
 *       "heading": "Chapter 1",
 *       "text": "Unit text content..."
 *     }
 *   ]
 * }
 */
async function importBook(jsonFilePath) {
    try {
        logger.info(`Importing book from ${jsonFilePath}`);

        const fileContent = await readFile(jsonFilePath, "utf-8");
        let bookData = JSON.parse(fileContent);

        // If the data is in shamela_crawler format, try to transform it
        // (This is a fallback - ideally use transform_shamela_json.js first)
        if (!bookData.units || !Array.isArray(bookData.units)) {
            logger.warn("JSON doesn't match expected format, attempting auto-transformation...");
            bookData = attemptAutoTransform(bookData);
        }

        // Validate structure
        if (!bookData.title || !bookData.units || !Array.isArray(bookData.units)) {
            throw new Error(
                "Invalid book JSON structure. Expected: {title, units[]}. " +
                "Please run transform_shamela_json.js first or check JSON format."
            );
        }

        // Check if book already exists
        const existingBooks = await bookRepository.findAll(1, 100, {
            title: bookData.title,
        });
        const existingBook = existingBooks.find((b) => b.title === bookData.title);

        if (existingBook) {
            logger.warn(
                `Book "${bookData.title}" already exists (ID: ${existingBook.id}). Skipping import.`
            );
            return existingBook;
        }

        // Create book
        const book = await bookRepository.create({
            title: bookData.title,
            author: bookData.author || null,
            description: bookData.description || null,
            category: bookData.category || null,
            language: bookData.language || "ar",
        });

        logger.info(`Created book: ${book.id} - ${book.title}`);

        // Create units
        const units = bookData.units.map((unit, idx) => ({
            book_id: book.id,
            index: unit.index !== undefined ? unit.index : idx + 1,
            heading: unit.heading || null,
            text: unit.text || "",
            metadata: unit.metadata || null,
        }));

        // Insert units in batches to avoid overwhelming the database
        const batchSize = 100;
        let insertedCount = 0;
        for (let i = 0; i < units.length; i += batchSize) {
            const batch = units.slice(i, i + batchSize);
            await unitRepository.createMany(batch);
            insertedCount += batch.length;
            logger.info(
                `Inserted units ${i + 1} to ${Math.min(
                    i + batchSize,
                    units.length
                )} (${insertedCount}/${units.length})`
            );
        }

        logger.info(
            `Successfully imported book ${book.id} with ${units.length} units`
        );
        return book;
    } catch (error) {
        logger.error(`Failed to import book from ${jsonFilePath}:`, error);
        throw error;
    }
}

async function main() {
    const args = process.argv.slice(2);

    if (args.length === 0) {
        console.log(
            "Usage: node scripts/importBooks.js <json-file-1> [json-file-2] ..."
        );
        console.log(
            "Example: node scripts/importBooks.js ../data/book1.json ../data/book2.json"
        );
        process.exit(1);
    }

    const dataDir = join(__dirname, "../../data");
    let successCount = 0;
    let failCount = 0;

    for (const fileArg of args) {
        const jsonFilePath = fileArg.startsWith("/") || fileArg.startsWith("..")
            ? fileArg
            : join(dataDir, fileArg);

        try {
            await importBook(jsonFilePath);
            successCount++;
        } catch (error) {
            logger.error(`Failed to import ${fileArg}:`, error);
            failCount++;
            // Continue with next file
        }
    }

    logger.info(
        `Import process completed: ${successCount} succeeded, ${failCount} failed`
    );
    process.exit(failCount > 0 ? 1 : 0);
}

main();
